formatter: markdown table
version: ""
header-from: main.tf
footer-from: ""
content: ""
output:
  file: README.md
  mode: replace
  template: |-
    # Spiritual Formation
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    
output-values:
  enabled: false
  from: ""
sort:
  enabled: true
  by: name
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true
  indent: 4
  lockfile: true
  required: true
  sensitive: true
  type: true